{% set name = "region" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eef456ce1664f018457634337249011c99c65814d8b7f4e5dd56f5c9487e4145

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - geopandas
    - libpysal
    - networkx >=2.0.0
    - numpy >=1.10.4
    - pulp
    - scipy
    - scikit-learn

test:
  imports:
    - region

about:
  home: http://github.com/pysal/region
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Spatially-explicit regionalization with PySAL'

  description: |
    A package for spatially-explicit regionalization.
  doc_url: http://region.readthedocs.io/
  dev_url: https://github.com/pysal/region

extra:
  recipe-maintainers:
    - knaaptime
    - sjsrey
