travis:
  secure:
    BINSTAR_TOKEN: ShK+/ZTAA1mgzQ2+re1TXiLsjrlXZgy12CWvxenu66Z2pumwfc0X6cIY07z3RDSJtA5guqFu7+DpQQHt8m07iAQq9ZltQXXeNXgHmr4G3hbqHAfW7D/2Ao9KULob12+FOhoj6bjt5PWfpCVmguJplWeyKPHlk64cO/cVdIb71/5FjwRoqbZbUhln7Tksg9ghMKBwXndkvj2PqU9IqwXvKNSlVZDg3Py3UWIJAu+lMutx3FGGgqP2swSurdUn12nijdbcIBTkwsTcRxR/AmL5JuD/Nnw6bnpXFX7cZonGis/qJmjamWGf0UXTjV9lOUM/z1JP34c4LJTNJkccOLdoh1jkV8d+zNGnGzzbxKW6obHtNsrani/pMzSUF81w3vaVzhSzzHWmeXMHIVB+b31fVfqbIhlAXwHLhwRKceXto2BfufymgISj3Ir+QjHP6rM4w2TbwExgvuA78Nmthh0DdpFh7MDiN3ylTjxdqtTNBcKAW+mh6nTOIJpmB5TeHNOBD1oY9vNV3U7A8SlKBbuc0kKOucEYi8k41UH3jNowoMXD9RRNRQjtvvI3bjCUKQsAmPOOZKl1ysZ8skrODblA6zMyP6XPleKJcQ8S5FCUKuMz9mpKRw8BtDawgGUx0j1NZNUvd6QVkbz4E32cqpuF7PnY6vHfoaW6VEi1IzOGbqw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
